# Módulo 5 Tarefa 1
## Base de nascidos vivos do DataSUS
O DataSUS disponibiliza diversos arquivos de dados com relação a seus segurados, conforme a [lei da transparência de informações públicas](https://www.sisgov.com/transparencia-acesso-informacao/#:~:text=A%20Lei%20da%20Transpar%C3%AAncia%20(LC,em%20um%20site%20na%20internet.). 

Essas informações podem ser obtidas pela internet [aqui](http://www2.datasus.gov.br/DATASUS/index.php?area=0901&item=1). Como o processo de obtenção desses arquivos foge um pouco do nosso escopo, deixamos o arquivo ```SINASC_RO_2019.csv``` já como vai ser encontrado no DataSUS. O dicionário de dados está no arquivo ```estrutura_sinasc_para_CD.pdf``` (o nome do arquivo tal qual no portal do DataSUS).

### Nosso objetivo
Queremos deixar uma base organizada para podermos estudar a relação entre partos com risco para o bebê e algumas condições como tempo de parto, consultas de pré-natal etc.

#### Preparação da base
1. Carregue a base 'SINASC_RO_2019.csv'. Conte o número de registros e o número de registros não duplicados da base. Dica: você aprendeu um método que remove duplicados, encadeie este método com um outro método que conta o número de linhas. **Há linhas duplicadas?**  

2. Conte o número de valores *missing* por variável.  

3. Ok, no item anterior você deve ter achado pouco prático ler a informação de tantas variáveis, muitas delas nem devem ser interesantes. Então crie uma seleção dessa base somente com as colunas que interessam. São elas:
``` 
['LOCNASC', 'IDADEMAE', 'ESTCIVMAE', 'ESCMAE', 'QTDFILVIVO', 
    'GESTACAO', 'GRAVIDEZ', 'CONSULTAS', 'APGAR5'] 
```
Refaça a contagem de valores *missings*.  

4. Apgar é uma *nota* que o pediatra dá ao bebê quando nasce de acordo com algumas características associadas principalmente à respiração. Apgar 1 e Apgar 5 são as notas 1 e 5 minutos do nascimento. Apgar5 será a nossa variável de interesse principal. Então remova todos os registros com Apgar5 não preenchido. Para esta seleção, conte novamente o número de linhas e o número de *missings*.  

5. observe que as variáveis ```['ESTCIVMAE', 'CONSULTAS']``` possuem o código ```9```, que significa *ignorado*. Vamos assumir que o não preenchido é o mesmo que o código ```9```.<br>
6. Substitua os valores faltantes da quantitativa (```QTDFILVIVO```) por zero.  
7. Das restantes, decida que valore te parece mais adequado (um 'não preenchido' ou um valor 'mais provável' como no item anterior) e preencha. Justifique. Lembre-se de que tratamento de dados é trabalho do cientista, e que estamos tomando decisões a todo o momento - não há necessariamente certo e errado aqui.  
8. O Apgar possui uma classificação indicando se o bebê passou por asfixia:
- Entre 8 e 10 está em uma faixa 'normal'. 
- Entre 6 e 7, significa que o recém-nascido passou por 'asfixia leve'. 
- Entre 4 e 5 significa 'asfixia moderada'.
- Entre 0 e 3 significa 'asfixia severa'.  

Crie uma categorização dessa variável com essa codificação e calcule as frequências dessa categorização.  
<br>
9. Renomeie as variáveis para que fiquem no *snake case*, ou seja, em letras minúsculas, com um *underscore* entre as palávras. Dica: repare que se você não quiser criar um *dataframe* novo, você vai precisar usar a opção ```inplace = True```.

In [10]:
import pandas as pd
import requests

# 1) seu código aqui
df_sinasc = pd.read_csv('C:\\Users\\Renan\\Desktop\\Curso DataScience\\SINASC_RO_2019.csv')
print(sinasc.shape)
df_sinasc.drop_duplicates().shape
# Não há duplicados

(27028, 69)

(27028, 69)

In [11]:
# 2) seu código aqui
df_sinasc.isna().sum() # Soma de cada coluna

ORIGEM          0
CODESTAB      115
CODMUNNASC      0
LOCNASC         0
IDADEMAE        0
             ...
munResUf        0
munResLat       1
munResLon       1
munResAlt       1
munResArea      1
Length: 69, dtype: int64

In [15]:
# 3) seu código aqui
# lista coluna de interesse
colunas_interesse = ['LOCNASC', 'IDADEMAE', 'ESTCIVMAE', 'ESCMAE', 'QTDFILVIVO', 'GESTACAO', 'GRAVIDEZ', 'CONSULTAS', 'APGAR5']

# Crie um novo DataFrame selecionando apenas as colunas de interesse
df_selecionado = df_sinasc[colunas_interesse]

# Recontagem de valores missing
valores_faltantes = df_selecionado.isna()

# Use .sum() para contar os valores faltantes em cada coluna
contagem_valores_faltantes = valores_faltantes.sum()

print(contagem_valores_faltantes)

LOCNASC          0
IDADEMAE         0
ESTCIVMAE      317
ESCMAE         312
QTDFILVIVO    1573
GESTACAO      1232
GRAVIDEZ        79
CONSULTAS        0
APGAR5         103
dtype: int64

In [16]:
# 4) seu código aqui
# Remova os registros com valores ausentes em 'APGAR5'
df_selecionado = df_selecionado.dropna(subset=['APGAR5']) # subset = seleciona a coluna

# Conte o número de linhas no DataFrame após a remoção
total_registros = len(df_selecionado)

# Conte o número de valores ausentes em cada coluna
valores_faltantes_apos_remocao = df_selecionado.isna().sum()

# Exiba o número total de registros e a contagem de valores faltantes após a remoção
print('Total de registros após a remoção de valores faltantes:', total_registros)
print('Contagem de valores faltantes após a remoção:')
print(valores_faltantes_apos_remocao)

Total de registros após a remoção de valores faltantes: 26925
Contagem de valores faltantes após a remoção:
LOCNASC          0
IDADEMAE         0
ESTCIVMAE      315
ESCMAE         310
QTDFILVIVO    1566
GESTACAO      1216
GRAVIDEZ        76
CONSULTAS        0
APGAR5           0
dtype: int64

In [19]:
# 5) seu código aqui
import numpy as np

# Substitua o valor '9' por NaN nas colunas especificadas
colunas_para_substituir = ['ESTCIVMAE', 'CONSULTAS']
df_selecionado[colunas_para_substituir] = df_selecionado[colunas_para_substituir].replace(9, np.nan)

# Conte o número de valores ausentes em cada coluna
valores_faltantes_apos_substituicao = df_selecionado.isna().sum()

# Exiba a contagem de valores faltantes após a substituicao
print('Contagem valores faltantes após a substituição:')
print(valores_faltantes_apos_substituicao)

Contagem valores faltantes após a substituição:
LOCNASC          0
IDADEMAE         0
ESTCIVMAE      459
ESCMAE         310
QTDFILVIVO    1566
GESTACAO      1216
GRAVIDEZ        76
CONSULTAS       50
APGAR5           0
dtype: int64

In [21]:
# 6) Seu código aqui
# Substitua os valores faltantes por zero na coluna 'QTDFILVIVO'
df_selecionado['QTDFILVIVO'].fillna(0, inplace=True)
df_selecionado

,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,QTDFILVIVO,GESTACAO,GRAVIDEZ,CONSULTAS,APGAR5
0,1,19,5.0,8 a 11 anos,0.0,37 a 41 semanas,Única,4.0,10.0
1,1,29,2.0,8 a 11 anos,1.0,37 a 41 semanas,Única,4.0,9.0
2,1,37,NaN,8 a 11 anos,2.0,37 a 41 semanas,Única,4.0,10.0
3,1,30,5.0,12 anos ou mais,0.0,37 a 41 semanas,Única,3.0,10.0
4,1,30,2.0,8 a 11 anos,1.0,37 a 41 semanas,Única,4.0,10.0
...,...,...,...,...,...,...,...,...,...
27023,1,32,2.0,12 anos ou mais,1.0,32 a 36 semanas,Única,4.0,9.0
27024,1,19,1.0,8 a 11 anos,0.0,37 a 41 semanas,Única,4.0,9.0
27025,1,24,2.0,8 a 11 anos,0.0,37 a 41 semanas,Única,4.0,10.0
27026,1,21,2.0,8 a 11 anos,1.0,32 a 36 semanas,Única,4.0,9.0
27027,1,18,5.0,8 a 11 anos,1.0,37 a 41 semanas,Única,4.0,8.0

In [ ]:
# 7) seu código aqui
# Não achei necessário alterar mais nenhum dado, no meu ver todos estão justificados da maneira correta

In [23]:
# 8) seu código aqui
# Defina os intervalos de classificação
bins = [0, 3, 5, 7 ,10]
labels = ['asfixia severa', 'asfixia moderada', 'asfixia leve', 'normal']

# Crie uma nova coluna 'APGAR_categoria' com as categorias
df_selecionado['APGAR_categoria'] = pd.cut(df_selecionado['APGAR5'], bins=bins, labels=labels)

# Calcule as frequencias das categorias
frequencias = df_selecionado['APGAR_categoria'].value_counts()

print(frequencias)

APGAR_categoria
normal              26463
asfixia leve          320
asfixia moderada       68
asfixia severa         57
Name: count, dtype: int64

In [24]:
df_selecionado

,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,QTDFILVIVO,GESTACAO,GRAVIDEZ,CONSULTAS,APGAR5,APGAR_categoria
0,1,19,5.0,8 a 11 anos,0.0,37 a 41 semanas,Única,4.0,10.0,normal
1,1,29,2.0,8 a 11 anos,1.0,37 a 41 semanas,Única,4.0,9.0,normal
2,1,37,NaN,8 a 11 anos,2.0,37 a 41 semanas,Única,4.0,10.0,normal
3,1,30,5.0,12 anos ou mais,0.0,37 a 41 semanas,Única,3.0,10.0,normal
4,1,30,2.0,8 a 11 anos,1.0,37 a 41 semanas,Única,4.0,10.0,normal
...,...,...,...,...,...,...,...,...,...,...
27023,1,32,2.0,12 anos ou mais,1.0,32 a 36 semanas,Única,4.0,9.0,normal
27024,1,19,1.0,8 a 11 anos,0.0,37 a 41 semanas,Única,4.0,9.0,normal
27025,1,24,2.0,8 a 11 anos,0.0,37 a 41 semanas,Única,4.0,10.0,normal
27026,1,21,2.0,8 a 11 anos,1.0,32 a 36 semanas,Única,4.0,9.0,normal
27027,1,18,5.0,8 a 11 anos,1.0,37 a 41 semanas,Única,4.0,8.0,normal

In [25]:
# 9) seu código aqui
# Renomeie as variaveis para snake case
df_selecionado.rename(columns=lambda x: x.lower().replace(' ', '_'), inplace=True)

In [26]:
df_selecionado

,locnasc,idademae,estcivmae,escmae,qtdfilvivo,gestacao,gravidez,consultas,apgar5,apgar_categoria
0,1,19,5.0,8 a 11 anos,0.0,37 a 41 semanas,Única,4.0,10.0,normal
1,1,29,2.0,8 a 11 anos,1.0,37 a 41 semanas,Única,4.0,9.0,normal
2,1,37,NaN,8 a 11 anos,2.0,37 a 41 semanas,Única,4.0,10.0,normal
3,1,30,5.0,12 anos ou mais,0.0,37 a 41 semanas,Única,3.0,10.0,normal
4,1,30,2.0,8 a 11 anos,1.0,37 a 41 semanas,Única,4.0,10.0,normal
...,...,...,...,...,...,...,...,...,...,...
27023,1,32,2.0,12 anos ou mais,1.0,32 a 36 semanas,Única,4.0,9.0,normal
27024,1,19,1.0,8 a 11 anos,0.0,37 a 41 semanas,Única,4.0,9.0,normal
27025,1,24,2.0,8 a 11 anos,0.0,37 a 41 semanas,Única,4.0,10.0,normal
27026,1,21,2.0,8 a 11 anos,1.0,32 a 36 semanas,Única,4.0,9.0,normal
27027,1,18,5.0,8 a 11 anos,1.0,37 a 41 semanas,Única,4.0,8.0,normal